version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    container_name: myRedis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass notificationms

  notification-ms:
    container_name: notification-ms
    image: fun-notification-ms
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - SPRING_DATASOURCE_URL=redis://myRedis:6379
      - SPRING_DATASOURCE_PASSWORD=notificationms
